server:
  port: 8888
  servlet:
    context-path: /lesson7
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gb_products_db;MODE=PostgreSQL
    username: admin
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  h2:
    console:
      enabled: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000