server:
  port: 8888
  servlet:
    context-path: /lesson7
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gb_products_db;MODE=PostgreSQL
    username: admin
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  h2:
    console:
      enabled: true
