server:
  port: 4444
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: BackService
          uri: lb://BackService
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost