server:
  port: 11001
spring:
  application:
    name: BackService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gb_products_db;MODE=PostgreSQL
    username: admin
    password: 123456
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
